### ISSUE TITLE
Exported displacements have inside-out normals

### ISSUE THREAD

**Issue by chanoc1** [Terri00/TBSA#2]
Exported displacements will have their normals inside-out and dont seem to respect the normals assigned in Blender.

![image](https://user-images.githubusercontent.com/11383237/80294487-310e2280-871e-11ea-89e2-c1c26b8757aa.png)

**Comment by Terri00** [comment]
check if the UV's are mirrored

**Comment by chanoc1** [comment]
Yeah, that was it, thank you. This addon is pretty sick, just found out it supports materials as well.
